### ISSUE TITLE
it does't work

### ISSUE THREAD

**Issue by PengfeiM** [tmux-plugins/tmux-net-speed#16]
it just shows 0 in my status bar
when I run ./run_test.sh
it meet error: en0 eth0 wlan0 should .........bla bla

How can I fix this ?

**Comment by PengfeiM** [comment]
this is the error message
> en0 eth0 lo wlan0 should output space-delimited list of interfaces -v
> [FAILED]: should output space-delimited list of interfaces

**Comment by LinuxIsCool** [comment]
Getting the same result.

**Comment by blackheaven** [comment]
Actually, the test is designed to only have `eth0 wlan0` as interfaces, so it's normal it is failing.

However it displays nothing.

**Comment by taizilongxu** [comment]
Not work for mac OS, it works only in Linux

**Comment by PengfeiM** [comment]
alright, got it.
I'll close this issue
